plugins{id("com.android.application")
id("org.jetbrains.kotlin.android")
id("org.jetbrains.kotlin.plugin.compose")
id("org.jetbrains.kotlin.plugin.serialization")}
android{namespace="com.jarvis.assistant"
compileSdk=35
defaultConfig{applicationId="com.jarvis.assistant"
minSdk=26
targetSdk=35
versionCode=1
versionName="1.0"}
buildTypes{release{isMinifyEnabled=false}}
buildFeatures{compose=true}
compileOptions{sourceCompatibility=JavaVersion.VERSION_17
targetCompatibility=JavaVersion.VERSION_17}
kotlinOptions{jvmTarget="17"}}
dependencies{implementation("androidx.core:core-ktx:1.13.1")
implementation("androidx.activity:activity-compose:1.9.3")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
implementation(platform("androidx.compose:compose-bom:2024.10.01"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.material3:material3")
debugImplementation("androidx.compose.ui:ui-tooling")
implementation("com.google.android.gms:play-services-location:21.3.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")}